sudo: false
language: node_js
env:
  - FORCE_COLOR=1
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js: '8'
install: npm install
script: npm run validate
after_success: kcd-scripts travis-after-success
branches:
  only: master
